vich_uploader:
    db_driver: orm

    mappings:
        memes:
            uri_prefix: /images/memes
            upload_destination: '%kernel.project_dir%/public/images/memes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
